// Base data for the Perfumer's Bench, ported verbatim from the Byobu repo
// (Three Feifs system): 9 fundamentals, 17 named frequencies, 96 ingredients,
// and the real d40 common-recipes table (41 perfumes — roll 16 is both Bright
// and Frenzy). Source of truth lives in ./base.json, generated by the Byobu
// repo's app/build_data.py.

import raw from "./base.json";
import type {
  Fundamental,
  Named,
  Ingredient,
  Recipe,
  RecipeSlotEntry,
  RecipeCombo,
  Tier,
} from "../lib/types";

type RawIngredient = {
  name: string;
  page: number;
  color: string;
  emits: string[];
  minus: number;
  plus: number;
};
type RawRecipe = {
  id: string;
  roll: number;
  name: string;
  desc: string;
  tier: Tier;
  slots: RecipeSlotEntry[][];
  reqs: string[][];
  combos: RecipeCombo[];
};

const data = raw as unknown as {
  fundamentals: Fundamental[];
  named: Named[];
  ingredients: RawIngredient[];
  recipes: RawRecipe[];
};

// The rare ninth letter E is the Unknown frequency — the source data labels
// it "Evocation*" (a decoding guess), but its meaning is unknown.
export const fundamentals: Fundamental[] = data.fundamentals.map((f) =>
  f.id === "E" ? { ...f, school: "Unknown" } : f,
);
export const named: Named[] = data.named;

export const FUND: Record<string, Fundamental> = Object.fromEntries(
  fundamentals.map((f) => [f.id, f]),
);
export const NAMED: Record<string, Named> = Object.fromEntries(
  named.map((n) => [n.id, n]),
);

// The four named frequencies emitted by NO ingredient — only summonable via ⊕.
export const LEGENDARY = new Set<string>([
  "Laternical",
  "Malvesian",
  "Thurmistic",
  "Saspacian",
]);

// Display ordering: fundamentals then named, alphabetical within each category.
export const FUND_ORDER: string[] = fundamentals
  .map((f) => f.id)
  .sort((a, b) => a.localeCompare(b));
const NAMED_ORDER: string[] = named
  .map((n) => n.id)
  .sort((a, b) => a.localeCompare(b));

export const isNamed = (id: string): boolean => !!NAMED[id];
export const isFundamental = (id: string): boolean => !!FUND[id];

// A frequency's weight is how many fundamentals it expands to in total
// (fundamentals weigh 1). An ingredient's weight sums its emitted
// frequencies; a recipe's weight is its heaviest tuning — the same measure
// that sets the simple/advanced/legendary tiers.
export const freqWeight = (id: string): number => NAMED[id]?.weight ?? 1;
export const ingredientWeight = (ing: Ingredient): number =>
  ing.emits.reduce((sum, t) => sum + freqWeight(t), 0);
export const recipeWeight = (r: Recipe): number =>
  Math.max(...r.reqs.map((req) => req.reduce((s, t) => s + freqWeight(t), 0)));

export const PAGE_NAMES: Record<number, string> = {
  0: "I", 1: "II", 2: "III", 3: "IV", 4: "V", 5: "VI",
  6: "VII", 7: "VIII", 8: "IX", 9: "X", 10: "XI", 11: "XII",
};

// Every frequency id, fundamentals first then named — used for wildcard pickers
// and frequency filters.
export type FrequencyKind = "fundamental" | "named";
export const ALL_FREQUENCIES: { id: string; kind: FrequencyKind }[] = [
  ...FUND_ORDER.map((id) => ({ id, kind: "fundamental" as const })),
  ...NAMED_ORDER.map((id) => ({ id, kind: "named" as const })),
];

export const baseIngredients: Ingredient[] = data.ingredients.map((i) => ({
  key: `base:${i.name}`,
  name: i.name,
  emits: i.emits,
  strike: i.minus,
  wild: i.plus,
  color: i.color,
  page: i.page,
  source: { kind: "base" } as const,
}));

// Pure frequencies: single-frequency pseudo-ingredients (plus a pure strike ⊖
// and a pure wild ⊕) that drop a frequency straight into the brew with no
// ingredient behind it. Keyed "pure:*" — no crest artwork, so their `source`
// is a synthetic non-base kind and thumbnails fall back to a color chip.
const PURE_SOURCE = { kind: "user", userId: "pure", name: "pure" } as const;
export const pureIngredients: Ingredient[] = [
  ...ALL_FREQUENCIES.map((t) => ({
    key: `pure:${t.id}`,
    name: `Pure ${t.id}`,
    emits: [t.id],
    strike: 0,
    wild: 0,
    color:
      t.kind === "fundamental"
        ? FUND[t.id].color
        : LEGENDARY.has(t.id)
          ? "#C98A3C"
          : "#6FE3C4",
    source: PURE_SOURCE,
  })),
  {
    key: "pure:strike",
    name: "Pure Strike",
    emits: [],
    strike: 1,
    wild: 0,
    color: "#a855f7",
    source: PURE_SOURCE,
  },
  {
    key: "pure:wild",
    name: "Pure Wild",
    emits: [],
    strike: 0,
    wild: 1,
    color: "#C98A3C",
    source: PURE_SOURCE,
  },
];
export const isPureKey = (key: string): boolean => key.startsWith("pure:");

export const baseRecipes: Recipe[] = data.recipes.map((r) => ({
  key: `base:${r.id}`,
  name: r.name,
  roll: r.roll,
  tier: r.tier,
  reqs: r.reqs,
  slots: r.slots,
  combos: r.combos,
  desc: r.desc,
  source: { kind: "base" } as const,
}));
