// Base data for the Perfumer, compiled from Joe's ground truth by the
// Byobu repo (Three Feifs system): 9 fundamentals, 17 named frequencies, 96
// ingredients, and the real d40 common-recipes table (41 perfumes — roll 16 is
// both Bright and Frenzy). Source of truth lives in ./base.json, generated by
// Byobu's app/compile.py from app/transcription.py (facts + rulings).

import raw from "./base.json";
import type {
  Fundamental,
  Named,
  Ingredient,
  IngredientType,
  Perfume,
  PerfumeSlotEntry,
  Combo,
} from "../lib/types";

type RawIngredient = {
  name: string;
  page: number;
  color: string;
  type: IngredientType;
  emits: string[];
  strike: number;
  wild: number;
};
type RawPerfume = {
  id: string;
  roll: number;
  name: string;
  effect: string;
  slots: PerfumeSlotEntry[][];
  recipes: string[][];
  combos: Combo[];
};

const data = raw as unknown as {
  fundamentals: Fundamental[];
  named: Named[];
  types: Record<IngredientType, { d: string; fillRule: string }>;
  ingredients: RawIngredient[];
  perfumes: RawPerfume[];
};

// The three ingredient types (element icons from the cards), with their
// 24-box glyph paths extracted from the source PDFs.
export const TYPE_GLYPHS = data.types;
export const INGREDIENT_TYPES: IngredientType[] = ["plant", "animal", "mineral"];

export const fundamentals: Fundamental[] = data.fundamentals;
export const named: Named[] = data.named;

export const FUND: Record<string, Fundamental> = Object.fromEntries(
  fundamentals.map((f) => [f.id, f]),
);
export const NAMED: Record<string, Named> = Object.fromEntries(
  named.map((n) => [n.id, n]),
);

// Named frequencies with no direct emitter among the KNOWN ingredients —
// computed, not lore: ingredients are still being discovered, and these are
// reachable anyway by combining emitted frequencies, or by a wild ⊕.
const EMITTED = new Set<string>(data.ingredients.flatMap((i) => i.emits));
export const NO_DIRECT_EMITTER = new Set<string>(
  named.map((n) => n.id).filter((id) => !EMITTED.has(id)),
);

// Display ordering is by WEIGHT: fundamentals (weight 1, in the source's
// canonical order) first, then named frequencies lightest-to-heaviest
// (ties keep the source order).
export const FUND_ORDER: string[] = fundamentals.map((f) => f.id);
const NAMED_ORDER: string[] = [...named]
  .sort((a, b) => a.weight - b.weight)
  .map((n) => n.id);

export const isNamed = (id: string): boolean => !!NAMED[id];
export const isFundamental = (id: string): boolean => !!FUND[id];

// A frequency's weight is how many fundamentals it expands to in total
// (fundamentals weigh 1). An ingredient's weight sums its emitted
// frequencies; a perfume's weight is its heaviest recipe.
export const freqWeight = (id: string): number => NAMED[id]?.weight ?? 1;
export const ingredientWeight = (ing: Ingredient): number =>
  ing.emits.reduce((sum, t) => sum + freqWeight(t), 0);
export const perfumeWeight = (r: Perfume): number =>
  Math.max(...r.recipes.map((req) => req.reduce((s, t) => s + freqWeight(t), 0)));

export const PAGE_NAMES: Record<number, string> = {
  0: "I", 1: "II", 2: "III", 3: "IV", 4: "V", 5: "VI",
  6: "VII", 7: "VIII", 8: "IX", 9: "X", 10: "XI", 11: "XII",
};

// Every frequency id, fundamentals first then named — used for wild pickers
// and frequency filters.
export type FrequencyKind = "fundamental" | "named";
export const ALL_FREQUENCIES: { id: string; kind: FrequencyKind }[] = [
  ...FUND_ORDER.map((id) => ({ id, kind: "fundamental" as const })),
  ...NAMED_ORDER.map((id) => ({ id, kind: "named" as const })),
];

export const baseIngredients: Ingredient[] = data.ingredients.map((i) => ({
  key: `base:${i.name}`,
  name: i.name,
  emits: i.emits,
  strike: i.strike,
  wild: i.wild,
  color: i.color,
  type: i.type,
  page: i.page,
  source: { kind: "base" } as const,
}));

// Pure frequencies: single-frequency pseudo-ingredients (plus a pure strike ⊖
// and a pure wild ⊕) that drop a frequency straight into the brew with no
// ingredient behind it. Obtainable in-world by casting spells, so brews
// containing them are real. Keyed "pure:*" — no crest artwork, so their
// `source` is a synthetic non-base kind and thumbnails fall back to a chip.
const PURE_SOURCE = { kind: "user", userId: "pure", name: "pure" } as const;
export const pureIngredients: Ingredient[] = [
  ...ALL_FREQUENCIES.map((t) => ({
    key: `pure:${t.id}`,
    name: `Pure ${t.kind === "fundamental" ? FUND[t.id].school : t.id}`,
    emits: [t.id],
    strike: 0,
    wild: 0,
    color:
      t.kind === "fundamental"
        ? FUND[t.id].color
        : NO_DIRECT_EMITTER.has(t.id)
          ? "#C98A3C"
          : "#6FE3C4",
    source: PURE_SOURCE,
  })),
  {
    key: "pure:strike",
    name: "Pure Strike",
    emits: [],
    strike: 1,
    wild: 0,
    color: "#a855f7",
    source: PURE_SOURCE,
  },
  {
    key: "pure:wild",
    name: "Pure Wild",
    emits: [],
    strike: 0,
    wild: 1,
    color: "#C98A3C",
    source: PURE_SOURCE,
  },
];
export const isPureKey = (key: string): boolean => key.startsWith("pure:");

export const basePerfumes: Perfume[] = data.perfumes.map((r) => ({
  key: `base:${r.id}`,
  name: r.name,
  roll: r.roll,
  effect: r.effect,
  recipes: r.recipes,
  slots: r.slots,
  combos: r.combos,
  source: { kind: "base" } as const,
}));

// Single shared perfume lookup by key ("base:<id>"). Callers that need to
// resolve a perfume from an item/output key import this instead of rebuilding
// `new Map(basePerfumes.map(...))` locally.
export const PERFUME_BY_KEY: Map<string, Perfume> = new Map(
  basePerfumes.map((p) => [p.key, p]),
);
