import { describe, expect, it } from "vitest";

import { hash8 } from "../worker/jobs/graph-hash.mjs";
import {
  baselineText,
  collect,
  countByRule,
  diffAgainst,
  exportName,
  flagOf,
  keyOf,
  normalizeText,
  parseBaseline,
  registrarOf,
  repoPath,
  setsFlag,
} from "./removal-sensor.mjs";

/** One ast-grep `--json=stream` line, in the fields the sensor reads. */
function hit(ruleId, file, text, startLine, endLine = startLine, name = undefined) {
  return JSON.stringify({
    ruleId,
    file,
    text,
    range: { start: { line: startLine - 1 }, end: { line: endLine - 1 } },
    ...(name === undefined ? {} : { metaVariables: { single: { NAME: { text: name } } } }),
  });
}

/** A fake `git grep` over a map of path -> file text: every line that
 *  mentions one of the alternation's names as a word, `path:line:text`. Exit 1
 *  with nothing, as git does, when nothing matched. */
function fakeGit(files) {
  const calls = [];
  return {
    calls,
    git: (args) => {
      calls.push(args);
      const names = args[5].split("|").map((n) => n.replace(/\\\$/g, "$"));
      const out = [];
      for (const [file, text] of Object.entries(files)) {
        text.split("\n").forEach((line, i) => {
          if (names.some((n) => new RegExp(`(?<![\\w$])${n.replace(/\$/g, "\\$")}(?![\\w$])`).test(line))) {
            out.push(`${file}:${i + 1}:${line}`);
          }
        });
      }
      return out.length === 0 ? { ok: false, status: 1, stdout: "", error: "" } : { ok: true, status: 0, stdout: `${out.join("\n")}\n` };
    },
  };
}

const BODY = "{\n  const a = 1;\n  const b = 2;\n  const c = 3;\n  const d = 4;\n  const e = 5;\n  return a + b + c + d + e;\n}";

function world() {
  const files = {
    "app/one.ts": `export function used() {}\nexport const unused = 1;\nconst x = unused;\n`,
    "app/two.ts": `import { used } from "./one";\nused();\n`,
    "app/page/route.ts": `export async function GET() {}\n`,
    "convex/fns.ts": `export const hidden = internalMutation({});\nrun(internal.fns.hidden);\n`,
    "worker/job.mjs": `export function run({ force = false, quiet = false } = {}) { return force || quiet; }\n`,
    "worker/main.mjs": `run({ quiet: true });\nrun({ force: false });\n`,
  };
  const matches = [
    hit("duplicated-helper", "app\\one.ts", BODY, 10, 16),
    hit("duplicated-helper", "worker/job.mjs", BODY.replace("const a = 1;", "const a = 1; // same"), 20, 26),
    hit("duplicated-helper", "worker/main.mjs", "{ return 1; }", 3, 3),
    hit("dead-export", "app/one.ts", "export function used() {}", 1),
    hit("dead-export", "app/one.ts", "export const unused = 1;", 2),
    hit("dead-export", "app/page/route.ts", "export async function GET() {}", 1),
    hit("dead-export", "convex/fns.ts", "export const hidden = internalMutation({});", 1),
    hit("flag-not-deletion", "worker/job.mjs", "force = false", 1),
    hit("flag-not-deletion", "worker/job.mjs", "quiet = false", 1),
    hit("check-not-deletion", "worker/job.mjs", "a  &&   a", 5),
  ];
  const { git, calls } = fakeGit(files);
  // Shuffled, because ast-grep's order is its thread pool's and the output
  // must not depend on it.
  const shuffled = [...matches].reverse();
  return { io: { astGrep: () => `${shuffled.join("\n")}\n`, git }, calls };
}

describe("removal sensor", () => {
  it("finds each smell and nothing a framework or Convex reads by name", () => {
    const { io } = world();
    const lines = collect(io).map(keyOf);
    const body = hash8(normalizeText(BODY));
    expect(lines).toEqual([
      `check-not-deletion\tworker/job.mjs\t${hash8("a && a")}`,
      `dead-export\tapp/one.ts\t${hash8("export unused")}`,
      `duplicated-helper\tapp/one.ts\t${body}`,
      `duplicated-helper\tworker/job.mjs\t${body}`,
      `flag-not-deletion\tworker/job.mjs\t${hash8("flag force")}`,
    ]);
  });

  it("carries the estimate the controller ranks on", () => {
    const { io } = world();
    const helper = collect(io).find((v) => v.ruleId === "duplicated-helper");
    expect(helper).toMatchObject({ lines: 7, files: 2, line: 10 });
  });

  it("writes a byte-identical baseline for the same tree, whatever order the matches came in", () => {
    const first = baselineText(collect(world().io).map(keyOf));
    const second = baselineText(collect(world().io).map(keyOf));
    expect(second).toBe(first);
    expect(first.split("\n")[0]).toBe("# 5 violations, regenerated by the removal loop; do not edit by hand");
    expect(parseBaseline(first)).toHaveLength(5);
  });

  it("counts every rule even at zero", () => {
    expect(countByRule([])).toEqual({
      counts: { "check-not-deletion": 0, "dead-export": 0, "duplicated-helper": 0, "flag-not-deletion": 0 },
      total: 0,
    });
  });

  it("names what is new and what is gone against a baseline", () => {
    const live = collect(world().io);
    const { added, dropped } = diffAgainst(live.slice(1), [keyOf(live[0]), keyOf(live[1]), "dead-export\tgone.ts\t00000000"]);
    expect(added.map(keyOf)).toEqual(live.slice(2).map(keyOf));
    expect(dropped).toEqual([keyOf(live[0]), "dead-export\tgone.ts\t00000000"]);
  });

  it("reads git grep's exit 1 as no match and any other failure as a failure", () => {
    const io = {
      astGrep: () => hit("dead-export", "app/a.ts", "export const lonely = 1;", 1),
      git: () => ({ ok: false, status: 1, stdout: "", error: "" }),
    };
    expect(collect(io).map((v) => v.ruleId)).toEqual(["dead-export"]);
    const broken = { ...io, git: () => ({ ok: false, status: 128, stdout: "", error: "not a git repository" }) };
    expect(() => collect(broken)).toThrow(/git grep failed/);
  });

  it("batches names fifty to a grep", () => {
    const exports = Array.from({ length: 120 }, (_, i) => hit("dead-export", "app/a.ts", `export const n${i} = ${i};`, i + 1));
    const { git, calls } = fakeGit({});
    collect({ astGrep: () => exports.join("\n"), git });
    expect(calls).toHaveLength(3);
  });
});

describe("the resolution half, piece by piece", () => {
  it("reads an export's name, and none for a default or a destructuring", () => {
    expect(exportName("export async function go() {}")).toBe("go");
    expect(exportName("export type Shape = {}")).toBe("Shape");
    expect(exportName("export const { a, b } = make();")).toBeNull();
  });

  it("knows a Convex registration", () => {
    expect(registrarOf("export const x = internalQuery({")).toBe("internalQuery");
    expect(registrarOf("export const y: number = compute(1)")).toBe("compute");
    expect(registrarOf("export function z() {}")).toBeNull();
  });

  it("reads a flag and its default off either shape", () => {
    expect(flagOf({ text: "dryRun = false" })).toEqual({ name: "dryRun", fallback: "false" });
    expect(flagOf({ text: "options.write === true", name: "write" })).toEqual({ name: "write", fallback: "false" });
  });

  it("counts every way a caller can set a flag, and not passing the default", () => {
    const flag = { name: "force", fallback: "false" };
    expect(setsFlag("run({ force: true })", "a.mjs", flag)).toBe(true);
    expect(setsFlag("run({ force: argv.includes('--force') })", "a.mjs", flag)).toBe(true);
    expect(setsFlag("run({ dir, force })", "a.mjs", flag)).toBe(true);
    expect(setsFlag("    force,", "a.mjs", flag)).toBe(true);
    expect(setsFlag("opts.force = true;", "a.mjs", flag)).toBe(true);
    expect(setsFlag("<Row force />", "a.tsx", flag)).toBe(true);
    expect(setsFlag("  force={x}", "a.tsx", flag)).toBe(true);
    expect(setsFlag("run({ force: false })", "a.mjs", flag)).toBe(false);
    expect(setsFlag("function run({ force = false } = {}) {", "a.mjs", flag)).toBe(false);
    expect(setsFlag("  force: boolean;", "a.ts", flag)).toBe(false);
    expect(setsFlag("if (force) return;", "a.mjs", flag)).toBe(false);
  });

  it("spells a path forward-slashed on every platform", () => {
    expect(repoPath("app\\lib\\x.ts")).toBe("app/lib/x.ts");
    expect(repoPath("./app/x.ts")).toBe("app/x.ts");
  });

  it("normalizes indentation and comments out of an identity", () => {
    expect(normalizeText("{\n  a(); // note\n  /* block */ b();\n}")).toBe("{ a(); b(); }");
    expect(normalizeText('fetch("https://x.y/z")')).toBe('fetch("https://x.y/z")');
  });
});
