// Generated by scripts/gen-explainers.mjs from every app/**/*.explainer.html. Do not edit.

export type ExplainerId = "frame";

export const EXPLAINERS: Record<ExplainerId, { title: string; load: () => Promise<{ default: string }> }> = {
  "frame": {
    title: "The frame",
    load: () => import("./explainers/frame.generated"),
  },
};
